#[derive(Clone, Debug, Default, PartialEq)]
pub struct PhoenixScores {
    pub favorite_score: Option<f64>,
    pub reply_score: Option<f64>,
    pub retweet_score: Option<f64>,
    pub photo_expand_score: Option<f64>,
    pub video_open_score: Option<f64>,
    pub click_score: Option<f64>,
    pub open_link_score: Option<f64>,
    pub profile_click_score: Option<f64>,
    pub vqv_score: Option<f64>,
    pub share_score: Option<f64>,
    pub share_via_dm_score: Option<f64>,
    pub share_via_copy_link_score: Option<f64>,
    pub dwell_score: Option<f64>,
    pub quote_score: Option<f64>,
    pub quoted_click_score: Option<f64>,
    pub quoted_vqv_score: Option<f64>,
    pub follow_author_score: Option<f64>,
    pub not_interested_score: Option<f64>,
    pub block_author_score: Option<f64>,
    pub mute_author_score: Option<f64>,
    pub report_score: Option<f64>,
    pub not_dwelled_score: Option<f64>,
    pub post_unexplored_score: Option<f64>,
    pub dwell_time: Option<f64>,
    pub click_dwell_time: Option<f64>,
    pub home_video_continuation_secs: Option<f64>,
    pub home_profile_visit_secs: Option<f64>,
}
