load_generator: "com.twitter.media_understanding.media_model_proxy.loadtest.MediaModelProxyLoadTestConfig"
rps: 100
duration:
  time: 10
feeder:
  feed_source:
    log:
      file: "logs/media-model-proxy-sample.csv"
transport:
  destinations:
    - victim: "/cluster/smf1/media-model-proxy/staging/media-model-proxy"
  scheme:
    thrift:
      num_clients: 1
